version: '3.8'

services:
  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  api:
    build: .
    ports:
      - '4000:4000'
    environment:
      - DATABASE_URL=mongodb://admin:password@mongo:27017/luminal_agent?authSource=admin
      - JWT_ACCESS_SECRET=super_secret_access
      - JWT_REFRESH_SECRET=super_secret_refresh
      - NODE_ENV=development
    depends_on:
      - mongo

volumes:
  mongo_data:
